[2022-10-14T15:25:04.533+0800] {processor.py:156} INFO - Started process (PID=214655) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:25:04.533+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:25:04.534+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:25:04.534+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:25:04.544+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:25:04.544+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:25:04.544+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:25:04.544+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:25:04.545+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:25:04.550+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2022-10-14T15:25:44.645+0800] {processor.py:156} INFO - Started process (PID=214731) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:25:44.646+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:25:44.646+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:25:44.646+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:25:44.657+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:25:44.657+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:25:44.657+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:25:44.657+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:25:44.657+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:25:44.663+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-10-14T15:26:51.423+0800] {processor.py:156} INFO - Started process (PID=214932) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:26:51.424+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:26:51.425+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:26:51.425+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:26:51.436+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:26:51.436+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:26:51.436+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:26:51.436+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:26:51.436+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:26:51.443+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T15:27:27.679+0800] {processor.py:156} INFO - Started process (PID=215193) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:27:27.680+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:27:27.680+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:27:27.680+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:27:27.691+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:27:27.691+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:27:27.692+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:27:27.691+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:27:27.692+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:27:27.698+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T15:28:02.539+0800] {processor.py:156} INFO - Started process (PID=215309) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:28:02.540+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:28:02.542+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:28:02.542+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:28:02.552+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:28:02.552+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:28:02.552+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:28:02.552+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:28:02.553+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:28:02.560+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-10-14T15:28:39.953+0800] {processor.py:156} INFO - Started process (PID=215697) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:28:39.954+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:28:39.954+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:28:39.954+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:28:39.965+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:28:39.964+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:28:39.965+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:28:39.965+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:28:39.965+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:28:39.971+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:29:12.580+0800] {processor.py:156} INFO - Started process (PID=216064) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:29:12.580+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:29:12.581+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:29:12.581+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:29:12.597+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:29:12.596+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:29:12.597+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:29:12.597+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:29:12.597+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:29:12.604+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-10-14T15:29:48.597+0800] {processor.py:156} INFO - Started process (PID=216382) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:29:48.598+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:29:48.598+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:29:48.598+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:29:48.613+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:29:48.613+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:29:48.613+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:29:48.613+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:29:48.614+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:29:48.621+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-10-14T15:30:24.209+0800] {processor.py:156} INFO - Started process (PID=216441) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:30:24.209+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:30:24.210+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:30:24.210+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:30:24.221+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:30:24.221+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:30:24.222+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:30:24.221+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:30:24.222+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:30:24.229+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-10-14T15:31:00.811+0800] {processor.py:156} INFO - Started process (PID=216552) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:31:00.812+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:31:00.812+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:31:00.812+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:31:00.827+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:31:00.827+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:31:00.827+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:31:00.827+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:31:00.828+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:31:00.838+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2022-10-14T15:31:38.643+0800] {processor.py:156} INFO - Started process (PID=216684) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:31:38.644+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:31:38.644+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:31:38.644+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:31:38.662+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:31:38.661+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:31:38.662+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:31:38.662+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:31:38.662+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:31:38.672+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2022-10-14T15:32:13.859+0800] {processor.py:156} INFO - Started process (PID=216759) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:32:13.860+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:32:13.861+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:32:13.861+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:32:13.877+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:32:13.876+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:32:13.877+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:32:13.877+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:32:13.877+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:32:13.887+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2022-10-14T15:32:49.964+0800] {processor.py:156} INFO - Started process (PID=216821) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:32:49.966+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:32:49.967+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:32:49.966+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:32:49.979+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:32:49.979+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:32:49.979+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:32:49.979+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:32:49.979+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:32:49.986+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-10-14T15:33:26.338+0800] {processor.py:156} INFO - Started process (PID=216891) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:33:26.338+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:33:26.339+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:33:26.339+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:33:26.350+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:33:26.349+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:33:26.350+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:33:26.350+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:33:26.350+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:33:26.357+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T15:34:02.600+0800] {processor.py:156} INFO - Started process (PID=216964) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:34:02.601+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:34:02.601+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:34:02.601+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:34:02.612+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:34:02.612+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:34:02.612+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:34:02.612+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:34:02.613+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:34:02.620+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-10-14T15:34:37.460+0800] {processor.py:156} INFO - Started process (PID=217163) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:34:37.461+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:34:37.461+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:34:37.461+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:34:37.474+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:34:37.473+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:34:37.474+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:34:37.474+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:34:37.474+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:34:37.481+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-10-14T15:35:10.919+0800] {processor.py:156} INFO - Started process (PID=217244) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:35:10.926+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:35:10.927+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:35:10.927+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:35:10.945+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:35:10.945+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:35:10.946+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:35:10.946+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:35:10.946+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:35:10.956+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2022-10-14T15:35:45.902+0800] {processor.py:156} INFO - Started process (PID=217371) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:35:45.903+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:35:45.904+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:35:45.904+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:35:45.914+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:35:45.913+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:35:45.914+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:35:45.914+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:35:45.914+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:35:45.920+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:36:21.764+0800] {processor.py:156} INFO - Started process (PID=217427) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:36:21.764+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:36:21.765+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:36:21.765+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:36:21.774+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:36:21.774+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:36:21.774+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:36:21.774+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:36:21.774+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:36:21.780+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2022-10-14T15:36:58.010+0800] {processor.py:156} INFO - Started process (PID=217500) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:36:58.011+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:36:58.012+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:36:58.011+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:36:58.024+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:36:58.023+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:36:58.024+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:36:58.024+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:36:58.024+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:36:58.032+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T15:37:32.340+0800] {processor.py:156} INFO - Started process (PID=217554) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:37:32.341+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:37:32.341+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:37:32.341+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:37:32.352+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:37:32.352+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:37:32.352+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:37:32.352+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:37:32.352+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:37:32.359+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T15:38:07.719+0800] {processor.py:156} INFO - Started process (PID=217630) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:38:07.720+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:38:07.721+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:38:07.720+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:38:07.732+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:38:07.732+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:38:07.732+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:38:07.732+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:38:07.732+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:38:07.741+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T15:38:42.370+0800] {processor.py:156} INFO - Started process (PID=217735) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:38:42.371+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:38:42.371+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:38:42.371+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:38:42.385+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:38:42.385+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:38:42.385+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:38:42.385+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:38:42.385+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:38:42.392+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T15:39:17.570+0800] {processor.py:156} INFO - Started process (PID=217856) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:39:17.571+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:39:17.572+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:39:17.571+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:39:17.582+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:39:17.582+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:39:17.582+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:39:17.582+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:39:17.583+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:39:17.589+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:39:50.590+0800] {processor.py:156} INFO - Started process (PID=217968) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:39:50.591+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:39:50.591+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:39:50.591+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:39:50.604+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:39:50.603+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:39:50.604+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:39:50.604+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:39:50.604+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:39:50.611+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T15:40:24.774+0800] {processor.py:156} INFO - Started process (PID=218170) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:40:24.776+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:40:24.776+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:40:24.776+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:40:24.788+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:40:24.788+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:40:24.789+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:40:24.788+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:40:24.789+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:40:24.796+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-10-14T15:40:59.586+0800] {processor.py:156} INFO - Started process (PID=218397) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:40:59.586+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:40:59.587+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:40:59.587+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:40:59.597+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:40:59.596+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:40:59.597+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:40:59.597+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:40:59.597+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:40:59.603+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2022-10-14T15:41:33.660+0800] {processor.py:156} INFO - Started process (PID=218461) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:41:33.660+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:41:33.661+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:41:33.661+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:41:33.671+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:41:33.671+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:41:33.671+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:41:33.671+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:41:33.671+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:41:33.677+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:42:09.353+0800] {processor.py:156} INFO - Started process (PID=218673) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:42:09.354+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:42:09.355+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:42:09.355+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:42:09.367+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:42:09.366+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:42:09.367+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:42:09.367+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:42:09.367+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:42:09.375+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T15:42:46.151+0800] {processor.py:156} INFO - Started process (PID=218865) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:42:46.152+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:42:46.152+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:42:46.152+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:42:46.165+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:42:46.165+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:42:46.165+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:42:46.165+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:42:46.165+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:42:46.172+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-10-14T15:43:21.480+0800] {processor.py:156} INFO - Started process (PID=218979) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:43:21.481+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:43:21.482+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:43:21.482+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:43:21.500+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:43:21.500+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:43:21.500+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:43:21.500+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:43:21.500+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:43:21.509+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2022-10-14T15:43:56.640+0800] {processor.py:156} INFO - Started process (PID=219074) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:43:56.640+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:43:56.641+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:43:56.641+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:43:56.651+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:43:56.651+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:43:56.651+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:43:56.651+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:43:56.652+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:43:56.658+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T15:44:32.578+0800] {processor.py:156} INFO - Started process (PID=219189) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:44:32.579+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:44:32.579+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:44:32.579+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:44:32.591+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:44:32.590+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:44:32.591+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:44:32.591+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:44:32.591+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:44:32.598+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-10-14T15:45:06.993+0800] {processor.py:156} INFO - Started process (PID=219293) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:45:06.994+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:45:06.994+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:45:06.994+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:45:07.007+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:45:07.007+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:45:07.007+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:45:07.007+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:45:07.008+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:45:07.015+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-10-14T15:45:43.787+0800] {processor.py:156} INFO - Started process (PID=219436) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:45:43.788+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:45:43.788+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:45:43.788+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:45:43.798+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:45:43.798+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:45:43.798+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:45:43.798+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:45:43.799+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:45:43.805+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:46:20.088+0800] {processor.py:156} INFO - Started process (PID=219676) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:46:20.115+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:46:20.116+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:46:20.115+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:46:20.128+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:46:20.128+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:46:20.128+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:46:20.128+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:46:20.129+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:46:20.137+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.051 seconds
[2022-10-14T15:46:58.048+0800] {processor.py:156} INFO - Started process (PID=219819) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:46:58.049+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:46:58.049+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:46:58.049+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:46:58.064+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:46:58.064+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:46:58.064+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:46:58.064+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:46:58.065+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:46:58.074+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-10-14T15:47:34.450+0800] {processor.py:156} INFO - Started process (PID=219919) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:47:34.451+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:47:34.451+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:47:34.451+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:47:34.462+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:47:34.461+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:47:34.462+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:47:34.462+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:47:34.462+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:47:34.469+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T15:48:10.071+0800] {processor.py:156} INFO - Started process (PID=220008) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:48:10.071+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:48:10.072+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:48:10.072+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:48:10.083+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:48:10.082+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:48:10.083+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:48:10.083+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:48:10.083+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:48:10.089+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:48:45.216+0800] {processor.py:156} INFO - Started process (PID=220114) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:48:45.216+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:48:45.217+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:48:45.217+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:48:45.230+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:48:45.229+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:48:45.230+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:48:45.230+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:48:45.230+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:48:45.239+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-10-14T15:49:21.026+0800] {processor.py:156} INFO - Started process (PID=220222) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:49:21.027+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:49:21.028+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:49:21.028+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:49:21.048+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:49:21.047+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:49:21.048+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:49:21.048+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:49:21.048+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:49:21.058+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2022-10-14T15:49:57.238+0800] {processor.py:156} INFO - Started process (PID=220373) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:49:57.239+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:49:57.239+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:49:57.239+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:49:57.250+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:49:57.249+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:49:57.250+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:49:57.250+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:49:57.250+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:49:57.256+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T15:50:33.854+0800] {processor.py:156} INFO - Started process (PID=220506) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:50:33.855+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:50:33.856+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:50:33.856+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:50:33.872+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:50:33.871+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:50:33.872+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:50:33.872+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:50:33.872+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:50:33.880+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-10-14T15:51:10.352+0800] {processor.py:156} INFO - Started process (PID=220647) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:51:10.352+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:51:10.353+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:51:10.353+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:51:10.364+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:51:10.364+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:51:10.364+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:51:10.364+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:51:10.365+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:51:10.372+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-10-14T15:52:06.452+0800] {processor.py:156} INFO - Started process (PID=220767) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:52:06.453+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:52:06.453+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:52:06.453+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:52:06.463+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:52:06.463+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:52:06.464+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:52:06.464+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:52:06.464+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:52:06.470+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:52:42.188+0800] {processor.py:156} INFO - Started process (PID=220889) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:52:42.189+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:52:42.190+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:52:42.190+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:52:42.200+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:52:42.200+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:52:42.200+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:52:42.200+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:52:42.201+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:52:42.207+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:53:21.486+0800] {processor.py:156} INFO - Started process (PID=220965) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:53:21.487+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:53:21.488+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:53:21.488+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:53:21.498+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:53:21.498+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:53:21.498+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:53:21.498+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:53:21.499+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:53:21.505+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T15:54:32.265+0800] {processor.py:156} INFO - Started process (PID=221219) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:54:32.266+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:54:32.266+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:54:32.266+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:54:32.281+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:54:32.280+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:54:32.281+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:54:32.281+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:54:32.281+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:54:32.290+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-10-14T15:55:10.354+0800] {processor.py:156} INFO - Started process (PID=221305) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:55:10.355+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:55:10.355+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:55:10.355+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:55:10.373+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:55:10.373+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:55:10.373+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:55:10.373+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:55:10.374+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:55:10.384+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2022-10-14T15:55:44.720+0800] {processor.py:156} INFO - Started process (PID=221425) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:55:44.721+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:55:44.722+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:55:44.722+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:55:44.741+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:55:44.740+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:55:44.741+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:55:44.741+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:55:44.741+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:55:44.755+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2022-10-14T15:56:20.532+0800] {processor.py:156} INFO - Started process (PID=221584) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:56:20.533+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:56:20.534+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:56:20.534+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:56:20.577+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:56:20.576+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:56:20.578+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:56:20.578+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:56:20.579+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:56:20.595+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2022-10-14T15:59:14.291+0800] {processor.py:156} INFO - Started process (PID=221852) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:59:14.292+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:59:14.293+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:59:14.292+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:59:14.303+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:59:14.303+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:59:14.304+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:59:14.304+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:59:14.304+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:59:14.310+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T15:59:50.581+0800] {processor.py:156} INFO - Started process (PID=221953) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:59:50.582+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T15:59:50.582+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:59:50.582+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:59:50.593+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:59:50.592+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T15:59:50.593+0800] {logging_mixin.py:117} INFO - [2022-10-14T15:59:50.593+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T15:59:50.593+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T15:59:50.599+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:00:25.356+0800] {processor.py:156} INFO - Started process (PID=222143) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:00:25.357+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:00:25.358+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:00:25.357+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:00:25.368+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:00:25.368+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:00:25.369+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:00:25.368+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:00:25.369+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:00:25.379+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-10-14T16:01:00.772+0800] {processor.py:156} INFO - Started process (PID=222255) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:01:00.773+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:01:00.773+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:01:00.773+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:01:00.785+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:01:00.785+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:01:00.785+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:01:00.785+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:01:00.785+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:01:00.791+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:01:36.207+0800] {processor.py:156} INFO - Started process (PID=222301) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:01:36.207+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:01:36.208+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:01:36.208+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:01:36.218+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:01:36.218+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:01:36.218+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:01:36.218+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:01:36.218+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:01:36.224+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2022-10-14T16:02:11.792+0800] {processor.py:156} INFO - Started process (PID=222371) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:02:11.793+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:02:11.793+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:02:11.793+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:02:11.804+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:02:11.803+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:02:11.804+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:02:11.804+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:02:11.804+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:02:11.810+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:03:12.133+0800] {processor.py:156} INFO - Started process (PID=222468) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:03:12.134+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:03:12.134+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:03:12.134+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:03:12.146+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:03:12.145+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:03:12.146+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:03:12.146+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:03:12.146+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:03:12.154+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T16:03:47.994+0800] {processor.py:156} INFO - Started process (PID=222511) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:03:47.994+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:03:47.995+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:03:47.995+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:03:48.008+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:03:48.008+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:03:48.008+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:03:48.008+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:03:48.008+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:03:48.016+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-10-14T16:07:43.147+0800] {processor.py:156} INFO - Started process (PID=223346) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:07:43.148+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:07:43.149+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:07:43.149+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:07:43.164+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:07:43.163+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:07:43.164+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:07:43.164+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:07:43.164+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:07:43.172+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-10-14T16:08:19.927+0800] {processor.py:156} INFO - Started process (PID=223437) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:08:19.927+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:08:19.928+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:08:19.928+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:08:19.938+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:08:19.938+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:08:19.938+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:08:19.938+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:08:19.938+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:08:19.945+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:08:54.068+0800] {processor.py:156} INFO - Started process (PID=223554) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:08:54.068+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:08:54.069+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:08:54.069+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:08:54.081+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:08:54.081+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:08:54.081+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:08:54.081+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:08:54.081+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:08:54.088+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-10-14T16:09:27.442+0800] {processor.py:156} INFO - Started process (PID=223674) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:09:27.443+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:09:27.443+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:09:27.443+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:09:27.455+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:09:27.455+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:09:27.455+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:09:27.455+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:09:27.456+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:09:27.461+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:10:03.081+0800] {processor.py:156} INFO - Started process (PID=223922) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:10:03.082+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:10:03.082+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:10:03.082+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:10:03.093+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:10:03.092+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:10:03.093+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:10:03.093+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:10:03.093+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:10:03.099+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:10:39.102+0800] {processor.py:156} INFO - Started process (PID=224018) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:10:39.103+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:10:39.103+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:10:39.103+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:10:39.113+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:10:39.113+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:10:39.114+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:10:39.114+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:10:39.114+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:10:39.121+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:11:14.114+0800] {processor.py:156} INFO - Started process (PID=224119) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:11:14.115+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:11:14.115+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:11:14.115+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:11:14.126+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:11:14.126+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:11:14.126+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:11:14.126+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:11:14.126+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:11:14.133+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:11:49.154+0800] {processor.py:156} INFO - Started process (PID=224253) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:11:49.155+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:11:49.155+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:11:49.155+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:11:49.165+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:11:49.165+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:11:49.165+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:11:49.165+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:11:49.165+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:11:49.172+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:12:24.085+0800] {processor.py:156} INFO - Started process (PID=224356) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:12:24.086+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:12:24.086+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:12:24.086+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:12:24.096+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:12:24.096+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:12:24.097+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:12:24.097+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:12:24.097+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:12:24.105+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-10-14T16:12:59.475+0800] {processor.py:156} INFO - Started process (PID=224443) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:12:59.476+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:12:59.476+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:12:59.476+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:12:59.487+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:12:59.486+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:12:59.487+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:12:59.487+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:12:59.487+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:12:59.493+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:13:34.412+0800] {processor.py:156} INFO - Started process (PID=224533) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:13:34.413+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:13:34.413+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:13:34.413+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:13:34.423+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:13:34.423+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:13:34.423+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:13:34.423+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:13:34.423+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:13:34.430+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:14:08.369+0800] {processor.py:156} INFO - Started process (PID=224631) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:14:08.370+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:14:08.371+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:14:08.371+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:14:08.383+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:14:08.383+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:14:08.384+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:14:08.383+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:14:08.384+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:14:08.392+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-10-14T16:14:44.811+0800] {processor.py:156} INFO - Started process (PID=224867) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:14:44.812+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:14:44.813+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:14:44.813+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:14:44.823+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:14:44.823+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:14:44.823+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:14:44.823+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:14:44.824+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:14:44.830+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:15:19.771+0800] {processor.py:156} INFO - Started process (PID=224971) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:15:19.771+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:15:19.772+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:15:19.772+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:15:19.782+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:15:19.782+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:15:19.782+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:15:19.782+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:15:19.782+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:15:19.788+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:15:55.864+0800] {processor.py:156} INFO - Started process (PID=225012) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:15:55.865+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:15:55.865+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:15:55.865+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:15:55.875+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:15:55.875+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:15:55.876+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:15:55.876+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:15:55.876+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:15:55.882+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:16:30.337+0800] {processor.py:156} INFO - Started process (PID=225063) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:16:30.338+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:16:30.338+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:16:30.338+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:16:30.350+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:16:30.349+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:16:30.350+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:16:30.350+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:16:30.350+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:16:30.356+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-10-14T16:17:05.979+0800] {processor.py:156} INFO - Started process (PID=225117) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:17:05.980+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:17:05.980+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:17:05.980+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:17:05.990+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:17:05.990+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:17:05.990+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:17:05.990+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:17:05.990+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:17:05.997+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:17:39.811+0800] {processor.py:156} INFO - Started process (PID=225171) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:17:39.812+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:17:39.812+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:17:39.812+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:17:39.822+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:17:39.822+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:17:39.822+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:17:39.822+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:17:39.822+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:17:39.829+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:18:14.763+0800] {processor.py:156} INFO - Started process (PID=225222) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:18:14.763+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:18:14.764+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:18:14.764+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:18:14.774+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:18:14.774+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:18:14.774+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:18:14.774+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:18:14.775+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:18:14.781+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:18:47.987+0800] {processor.py:156} INFO - Started process (PID=225261) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:18:47.988+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:18:47.989+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:18:47.989+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:18:47.999+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:18:47.998+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:18:47.999+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:18:47.999+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:18:47.999+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:18:48.006+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:19:22.820+0800] {processor.py:156} INFO - Started process (PID=225305) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:19:22.821+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:19:22.821+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:19:22.821+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:19:22.831+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:19:22.831+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:19:22.831+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:19:22.831+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:19:22.831+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:19:22.838+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:27:08.643+0800] {processor.py:156} INFO - Started process (PID=226888) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:27:08.644+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:27:08.645+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:27:08.645+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:27:08.655+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:27:08.655+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:27:08.656+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:27:08.656+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:27:08.656+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:27:08.662+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:27:46.435+0800] {processor.py:156} INFO - Started process (PID=227158) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:27:46.436+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:27:46.437+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:27:46.437+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:27:46.447+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:27:46.446+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:27:46.447+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:27:46.447+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:27:46.447+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:27:46.453+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:28:26.909+0800] {processor.py:156} INFO - Started process (PID=227327) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:28:26.910+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:28:26.910+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:28:26.910+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:28:26.920+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:28:26.920+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:28:26.920+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:28:26.920+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:28:26.920+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:28:26.926+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2022-10-14T16:29:07.021+0800] {processor.py:156} INFO - Started process (PID=227395) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:29:07.022+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:29:07.022+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:29:07.022+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:29:07.033+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:29:07.033+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:29:07.033+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:29:07.033+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:29:07.034+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:29:07.040+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:29:49.472+0800] {processor.py:156} INFO - Started process (PID=227524) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:29:49.473+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:29:49.474+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:29:49.474+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:29:49.486+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:29:49.486+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:29:49.486+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:29:49.486+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:29:49.487+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:29:49.497+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2022-10-14T16:30:30.216+0800] {processor.py:156} INFO - Started process (PID=227640) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:30:30.217+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:30:30.218+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:30:30.217+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:30:30.230+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:30:30.229+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:30:30.230+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:30:30.230+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:30:30.230+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:30:30.238+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-10-14T16:31:08.436+0800] {processor.py:156} INFO - Started process (PID=227715) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:31:08.437+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:31:08.437+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:31:08.437+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:31:08.448+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:31:08.448+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:31:08.448+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:31:08.448+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:31:08.449+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:31:08.456+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-10-14T16:31:47.058+0800] {processor.py:156} INFO - Started process (PID=227799) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:31:47.059+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:31:47.060+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:31:47.060+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:31:47.070+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:31:47.070+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:31:47.070+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:31:47.070+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:31:47.071+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:31:47.077+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:32:23.815+0800] {processor.py:156} INFO - Started process (PID=227876) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:32:23.816+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:32:23.816+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:32:23.816+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:32:23.829+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:32:23.828+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:32:23.829+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:32:23.829+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:32:23.830+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:32:23.838+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-10-14T16:33:02.594+0800] {processor.py:156} INFO - Started process (PID=227946) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:33:02.595+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:33:02.595+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:33:02.595+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:33:02.606+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:33:02.605+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:33:02.606+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:33:02.606+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:33:02.606+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:33:02.613+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2022-10-14T16:33:44.726+0800] {processor.py:156} INFO - Started process (PID=228070) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:33:44.727+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:33:44.728+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:33:44.728+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:33:44.739+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:33:44.739+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:33:44.739+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:33:44.739+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:33:44.739+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:33:44.749+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-10-14T16:34:24.692+0800] {processor.py:156} INFO - Started process (PID=228131) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:34:24.692+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:34:24.693+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:34:24.693+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:34:24.705+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:34:24.704+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:34:24.705+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:34:24.705+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:34:24.705+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:34:24.712+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2022-10-14T16:35:07.298+0800] {processor.py:156} INFO - Started process (PID=228254) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:35:07.299+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:35:07.300+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:35:07.300+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:35:07.313+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:35:07.312+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:35:07.313+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:35:07.313+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:35:07.313+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:35:07.320+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T16:35:48.929+0800] {processor.py:156} INFO - Started process (PID=228414) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:35:48.930+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:35:48.931+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:35:48.931+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:35:48.944+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:35:48.943+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:35:48.944+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:35:48.944+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:35:48.944+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:35:48.952+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T16:36:26.314+0800] {processor.py:156} INFO - Started process (PID=228512) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:36:26.315+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:36:26.315+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:36:26.315+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:36:26.329+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:36:26.328+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:36:26.329+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:36:26.329+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:36:26.329+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:36:26.337+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2022-10-14T16:37:06.538+0800] {processor.py:156} INFO - Started process (PID=228620) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:37:06.539+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:37:06.540+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:37:06.540+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:37:06.552+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:37:06.551+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:37:06.552+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:37:06.552+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:37:06.552+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:37:06.562+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2022-10-14T16:37:46.380+0800] {processor.py:156} INFO - Started process (PID=228754) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:37:46.381+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:37:46.381+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:37:46.381+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:37:46.393+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:37:46.393+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:37:46.393+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:37:46.393+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:37:46.393+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:37:46.399+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:38:26.404+0800] {processor.py:156} INFO - Started process (PID=228905) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:38:26.405+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:38:26.405+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:38:26.405+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:38:26.417+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:38:26.416+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:38:26.417+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:38:26.417+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:38:26.417+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:38:26.425+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T16:39:14.978+0800] {processor.py:156} INFO - Started process (PID=229017) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:39:14.979+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:39:14.979+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:39:14.979+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:39:14.992+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:39:14.992+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:39:14.993+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:39:14.993+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:39:14.993+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:39:15.001+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2022-10-14T16:39:57.118+0800] {processor.py:156} INFO - Started process (PID=229185) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:39:57.119+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:39:57.120+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:39:57.120+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:39:57.137+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:39:57.136+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:39:57.137+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:39:57.137+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:39:57.138+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:39:57.147+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2022-10-14T16:40:41.144+0800] {processor.py:156} INFO - Started process (PID=229275) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:40:41.145+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:40:41.145+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:40:41.145+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:40:41.156+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:40:41.156+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:40:41.156+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:40:41.156+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:40:41.156+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:40:41.163+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2022-10-14T16:41:22.030+0800] {processor.py:156} INFO - Started process (PID=229342) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:41:22.031+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:41:22.032+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:41:22.032+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:41:22.053+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:41:22.052+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:41:22.053+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:41:22.053+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:41:22.053+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:41:22.067+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2022-10-14T16:41:59.976+0800] {processor.py:156} INFO - Started process (PID=229418) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:41:59.977+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:41:59.978+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:41:59.978+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:41:59.990+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:41:59.990+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:41:59.991+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:41:59.990+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:41:59.991+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:41:59.999+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2022-10-14T16:42:40.857+0800] {processor.py:156} INFO - Started process (PID=229539) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:42:40.859+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:42:40.860+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:42:40.859+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:42:40.883+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:42:40.882+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:42:40.883+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:42:40.883+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:42:40.884+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:42:40.897+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-10-14T16:43:24.493+0800] {processor.py:156} INFO - Started process (PID=229651) to work on /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:43:24.500+0800] {processor.py:758} INFO - Processing file /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-14T16:43:24.500+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:43:24.500+0800] {dagbag.py:525} INFO - Filling up the DagBag from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:43:24.512+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:43:24.512+0800] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-14T16:43:24.513+0800] {logging_mixin.py:117} INFO - [2022-10-14T16:43:24.513+0800] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-14T16:43:24.513+0800] {processor.py:770} WARNING - No viable dags retrieved from /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-14T16:43:24.520+0800] {processor.py:178} INFO - Processing /home/aurora/.local/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
